server:
  port: 8888
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    datasource:
      url: jdbc:mysql://localhost:3306/mybatis
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver